// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNoD9lBI4_YjaX_AoSlQTOMWbw8dJy2g',
    appId: '1:200838806725:web:0a16876169fccaf1d284ac',
    messagingSenderId: '200838806725',
    projectId: 'task-management-952ef',
    authDomain: 'task-management-952ef.firebaseapp.com',
    databaseURL: 'https://task-management-952ef-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-952ef.appspot.com',
    measurementId: 'G-YBTVT497GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkypURyDF-p-Niep0diTaIJYMsmpten4',
    appId: '1:200838806725:android:499d455c91ac8d63d284ac',
    messagingSenderId: '200838806725',
    projectId: 'task-management-952ef',
    databaseURL: 'https://task-management-952ef-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-952ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTpuXAEjiXH_nWPUYa1PWYOYlaiSrKx8',
    appId: '1:200838806725:ios:92ec65855cab9459d284ac',
    messagingSenderId: '200838806725',
    projectId: 'task-management-952ef',
    databaseURL: 'https://task-management-952ef-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-952ef.appspot.com',
    androidClientId: '200838806725-2pvqndp9f859bmpskdm3aonrgfsoamor.apps.googleusercontent.com',
    iosClientId: '200838806725-fk29va0tlj6att1nbc5bmhkuirtcd3a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

}